# Site config
baseurl: ""

# User config
author: "Daniel Shervheim"
description: "A Personal Portfolio."
email: "danielshervheim@gmail.com"

# Syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# User collections
collections:
  projects:
    output: true
  hidden_projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page
  - scope:
      path: ""
      type: "hidden_projects"
    values:
      layout: page
