# Site config
baseurl: ""

# User config
author: "Daniel Shervheim"
description: "A Personal Portfolio."
email: "danielshervheim@gmail.com"


# User collections
collections:
    projects:
        output: true
    coursework:
        output: true

# Collection defaults.
defaults:
-
    scope:
        path: "_projects"
        type: "projects"
    values:
        layout: page
-
    scope:
        path: "_coursework"
        type: "coursework"
    values:
        layout: page
